version: "3"
services:
  node-app: # the name of service or container
    build: . # the source of Dockerfile for this container
    ports: 
      - "3000:3000"
    volumes:
      # mean we will dump directories . into /app in container
      - ./src:/app/src
      # we wont dump to /app/node_modules
      - /app/node_modules
    env_file:
      # the path is relative to this docker-compoose
      - ./.env