version: "3"
services:
  node-app:
    build: 
      # path of Dockerfile
      context: .
      # pass argument to Dockerfile later
      args:
        NODE_ENV: development

    volumes:
      # bind volume ./src into /app/src in container
      - ./src:/app/src
      # anonymous voulume
      - /app/node_modules

    environment:
      - NODE_ENV=development

    # this command will override CMD in Dockerfile
    command: npm run dev