version: "3"
services:
  node-app:
    build: 
      # path of Dockerfile
      context: .
      # pass argument to Dockerfile later
      args:
        NODE_ENV: development

    volumes:
      # mean we will dump directories ./src into /app/src in container
      - ./src:/app/src
      # we wont dump to /app/node_modules
      - /app/node_modules

    environment:
      - NODE_ENV=development

    # this command will override CMD in Dockerfile
    command: npm run dev