version: "3"
services:

  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000


  postgres:
    image: postgres
    # define environtment for pg images, self-explanatory
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    # define named volumes to store data of postgres
    # so its survive when container is stopped
    volumes:
      - postgres-db:/data/db


  adminer:
    image: adminer
    ports:
      - "8080:8080"


volumes:
  postgres-db: